### ISSUE TITLE
You know what adjustments need to be made for MacBook M1 ? 

### ISSUE THREAD

**Issue by iddoeldor** [ant4g0nist/Sloth#1]
Except [here](https://github.com/ant4g0nist/Sloth/blob/main/Dockerfile#L27)

**Comment by ant4g0nist** [comment]
Hey! On M1, I was using android-ndk directly on the host itself, instead of docker! everything else can remain the same.
```sh
arch -x86_64 /bin/bash -c ~/android-ndk-r21e/ndk-build
```

**Comment by iddoeldor** [comment]
Sorry, Hey ! :) 
There is no working ndk for m1 :( 


BTW, great project, thank you for sharing !

**Comment by ant4g0nist** [comment]
yeah, i just used the intel version of ndk on M1 with the above `arch -x86_64` command! 

thank you! :) hope it's useful to you!
