### ISSUE TITLE
Can sloth support arm32 programs compiled by ndk?

### ISSUE THREAD

**Issue by Po1lux** [ant4g0nist/Sloth#2]
Hi,I want to modify your project to test the arm32 program, I copy the /system/ from a rooted Android device into resources/rootfs directory as you mentioned in the usage, but I got the error as blow:
`libc: error getting old personality value: Operation not permitted.`

I used the unmodified qemu to test and the same error occurred. So the error comes from qemu-arm. I searched for this error and found that the error was in the linker：
http://androidxref.com/6.0.0_r1/xref/bionic/libc/bionic/libc_init_common.cpp#__initialize_personality

` personality(0xffffffff); ` probability means to get the current process execution domain value, it seems that in the qemu-arm it returns -1. So I debug the qemu-arm, the relevant value in qemu is stored in info->personality, but until it runs to cpu_loop, this value is all 0. It may also be that the linker from the mobile phone does not have permission to obtain the value in qemu-arm.

I am confused why the aarch64 program compiled by ndk can be run directly in qemu-aarch, but the arm program compiled by ndk cannot be run in qemu-arm.

would you mind to give me some ideals? This problem has bothered me for a long time.

**Comment by ant4g0nist** [comment]
Hey!
Looks like the [personality](https://man7.org/linux/man-pages/man2/personality.2.html) syscall is failing. 

1) Are you running inside Docker? 
2) If so, could you please try running docker with --privileged 

Also, could you share on which host you are trying to do this?

**Comment by Po1lux** [comment]
All operations are done in the docker environment you provide: ubuntu 20.04 x86_64

**Comment by ant4g0nist** [comment]
okay, can you try running docker with `--privileged`?

**Comment by Po1lux** [comment]
Yes, it works! Thanks! I'm just trying to figure out why it works in aarch64 directly. I replied via email, but it doesn’t seem to be displayed here

**Comment by ant4g0nist** [comment]
Perfect!

So, `personality` is blocked as part of the seccomp profile! the execution might fail for 64-bit also, if some binary executes that syscall! 

Check the section `Significant syscalls blocked by the default profile` here https://docs.docker.com/engine/security/seccomp/

**Comment by Po1lux** [comment]
thanks! so nice you are :)

**Comment by ant4g0nist** [comment]
haha thank you :) let me know how it goes. all the best \m/

**Comment by Po1lux** [comment]
hey, I want to fuzz the arm32 program, so I made some changes to your project. Basically I just change some 64-bit content to 32-bit. And I got the first error, it seems that the value `target_addr` from `libQemuDlsym("libQemuFuzzerTestOneInput");` is a host addr, but in the cpu_loop function qemu treats it as a guest_addr,  the key function as below:
```
uint32_t cpu_ldl_code(CPUArchState *env, abi_ptr ptr)
{
    uint32_t ret;

    set_helper_retaddr(1);
    ret = ldl_p(g2h(ptr));
    clear_helper_retaddr();
    return ret;
}
```
the g2h function:
`#define g2h(x) ((void *)((unsigned long)(abi_ptr)(x) + guest_base))`

so the target_addr is added with guest_base(in AArch64, this value is 0), and point to a non-exist addr, so in the funtion `LLVMFuzzerTestOneInput` of main.c, i change the value which pass to cpu:
`regs->uregs[15] = regs->uregs[15]-guest_base;`

After that I got the second error:
```
==== SLOTH ====
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1372558353
INFO: 65536 Extra Counters
INFO:        0 files found in /examples/test/in
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
qemu: uncaught target signal 4 (Unknown signal 0) - core dumped
```
the gdb backtrace:
![image](https://user-images.githubusercontent.com/20920394/128850650-88f1c5ab-38ec-4641-8d20-7910eeea739b.png)

it seems that the host can'y deal with the syscall, my env is docker with ubuntu 20.04, and the container is created with args `--privileged`, do you have any ieads about this problem or sloth's support for arm32?

**Comment by Po1lux** [comment]
I found the source of the problem, F0 B5 03 AF is two ins:
```
PUSH            {R4-R7,LR}
ADD             R7, SP, #0xC
```

but it treats it as an instruction:
`swi #bignum`
so the host can'y deal with the syscall.

**Comment by Po1lux** [comment]
I modify the cpsr flag before running cpu_loop, it seems to start working:
```
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1913776623
INFO: 65536 Extra Counters
INFO:        0 files found in /examples/test/in
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
==22079== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000


artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64:
```

I got the third error...
![image](https://user-images.githubusercontent.com/20920394/128863373-0de11911-b203-48bd-a0a0-179313d93230.png)
