### ISSUE TITLE
booFuzz vs libFuzzer confusion

### ISSUE THREAD

**Issue by avgNobody** [ant4g0nist/Sloth#5]
Hi,
  So I'm a bit confused.  If this is using the libfuzzer engine, why do you have it using booFuzz?  Why is that being linked in the make file?

**Comment by ant4g0nist** [comment]
hey. Sorry for the confusion. [booFuzz](https://github.com/jtpereyda/boofuzz) has nothing to do with the booFuzz you are seeing in Sloth. it's just a random name I used for the compiled example library!

**Comment by avgNobody** [comment]
Thanks!  Also, I was looking around to see why you included libhwui.so  I guess it was aa Skia library?  I don't see it being used anywhere. :)

**Comment by avgNobody** [comment]
Android seems to have moved around this library and a few of the graphics dependencies in the later versions.

**Comment by ant4g0nist** [comment]
When I was building, the example project depended on the Android version. That's why the libhwui :)

**Comment by avgNobody** [comment]
I managed to get it all building, but  when running the command:
SLOTH_TARGET_LIBRARY=/rootfs/system/lib64/libBooFuzz.so ./sloth /rootfs/boofuzz test/
I seem to be getting a segfault.  Have you run into that or helped anyone that ran into this issue?
My backtrace seems to be
#0  __memset_avx2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:200
#1  0x00007f6c29c54779 in zero_bss (elf_bss=365072230992, last_bss=<optimized out>, prot=<optimized out>) at /sloth/src/qemu/linux-user/elfload.c:1817
#2  load_elf_image (image_name=<optimized out>, image_fd=<optimized out>, info=<optimized out>, pinterp_name=0x7ffd43389d88, bprm_buf=<optimized out>) at /sloth/src/qemu/linux-user/elfload.c:2550
#3  0x00007f6c29c52dd5 in load_elf_binary (bprm=0x7ffd4338a0e0, info=0x7ffd43389fe0) at /sloth/src/qemu/linux-user/elfload.c:2877
#4  0x00007f6c29c56531 in loader_exec (fdexec=<optimized out>, filename=<optimized out>, argv=<optimized out>, envp=<optimized out>, regs=0x7ffd4338a520, infop=0x7ffd43389fe0, bprm=0x7ffd4338a0e0)
    at /sloth/src/qemu/linux-user/linuxload.c:147
#5  0x00007f6c29c330e6 in libQemuInit (argc=2, argv=<optimized out>, envp=<optimized out>) at /sloth/src/qemu/linux-user/main.c:849
#6  0x0000000000404a37 in main ()

**Comment by avgNobody** [comment]
Oh sorry.  I forgot I had an open question.  I figured it out, so I'm good now.  Thanks!  And great stuff on Sloth man.  I appreciate the work you put into it.
